// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:objectbox/objectbox.dart';
import 'package:xflutter_cli_test_application/data/models/entities/category/category.dart';
import 'package:xflutter_cli_test_application/data/models/entities/media/media.dart';
import 'dart:convert' as convert;

@Entity()
class LocalCategory {
  @Id(assignable: true)
  int id;
  @Property(type: PropertyType.date)
  DateTime? createdAt;
  @Property(type: PropertyType.date)
  DateTime? updatedAt;
  String? name;
  List<String>? media;

  LocalCategory({required this.id, this.createdAt, this.updatedAt, this.name, this.media});

  /// convert [Category] to [LocalCategory]
  factory LocalCategory.fromEntity(Category entity) {
    final item = LocalCategory(
      id: entity.id ?? 0,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      name: entity.name,
      media: entity.media?.map((e) => convert.json.encode(e)).toList(),
    );

    return item;
  }

  /// convert [LocalCategory] to [Category]
  Category fromLocal() => Category(
    id: id,
    createdAt: createdAt,
    updatedAt: updatedAt,
    name: name,
    media: media?.map((e) => Media.fromJson(convert.json.decode(e))).toList(),
  );
}
