// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:isar/isar.dart';
import 'package:xflutter_cli_modules_application/common/models/models.dart';
import '../isar_models.dart';

part 'product.g.dart';

@collection
class IsarProduct {
  Id? isarId;

  @Index(unique: true, replace: true)
  int? id;
  String? title;
  String? description;
  String? category;
  double? price;
  double? discountPercentage;
  double? rating;
  int? stock;
  List<String>? tags;
  String? brand;
  String? sku;
  int? weight;
  IsarDimensions? dimensions;
  String? warrantyInformation;
  String? shippingInformation;
  String? availabilityStatus;
  List<IsarReviews>? reviews;
  String? returnPolicy;
  int? minimumOrderQuantity;
  IsarMeta? meta;
  List<String>? images;
  String? thumbnail;

  IsarProduct({
    this.id,
    this.title,
    this.description,
    this.category,
    this.price,
    this.discountPercentage,
    this.rating,
    this.stock,
    this.tags,
    this.brand,
    this.sku,
    this.weight,
    this.dimensions,
    this.warrantyInformation,
    this.shippingInformation,
    this.availabilityStatus,
    this.reviews,
    this.returnPolicy,
    this.minimumOrderQuantity,
    this.meta,
    this.images,
    this.thumbnail,
  });
}

extension IsarProductConverter on IsarProduct {
  /// convert [IsarProduct] to [Product]
  Product fromIsar() {
    return Product(
      id: id,
      title: title,
      description: description,
      category: category,
      price: price,
      discountPercentage: discountPercentage,
      rating: rating,
      stock: stock,
      tags: tags,
      brand: brand,
      sku: sku,
      weight: weight,
      dimensions: dimensions?.fromIsar(),
      warrantyInformation: warrantyInformation,
      shippingInformation: shippingInformation,
      availabilityStatus: availabilityStatus,
      reviews: reviews?.map((e) => e.fromIsar()).toList(),
      returnPolicy: returnPolicy,
      minimumOrderQuantity: minimumOrderQuantity,
      meta: meta?.fromIsar(),
      images: images,
      thumbnail: thumbnail,
    );
  }
}

extension ProductConverter on Product {
  /// convert [Product] to [IsarProduct]
  IsarProduct toIsar() {
    return IsarProduct(
      id: id,
      title: title,
      description: description,
      category: category,
      price: price?.toDouble(),
      discountPercentage: discountPercentage?.toDouble(),
      rating: rating?.toDouble(),
      stock: stock,
      tags: tags,
      brand: brand,
      sku: sku,
      weight: weight,
      dimensions: dimensions?.toIsar(),
      warrantyInformation: warrantyInformation,
      shippingInformation: shippingInformation,
      availabilityStatus: availabilityStatus,
      reviews: reviews?.map((e) => e.toIsar()).toList(),
      returnPolicy: returnPolicy,
      minimumOrderQuantity: minimumOrderQuantity,
      meta: meta?.toIsar(),
      images: images,
      thumbnail: thumbnail,
    );
  }
}
