/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:animated_infinite_scroll_pagination/animated_infinite_scroll_pagination.dart';
import 'package:core/src/ui/widgets/core/base_scrollview.dart';
import '../animations/customized_animated_widget.dart';
import '../loaders/loader.dart';
import 'pagination_load_widget.dart';
import 'pagination_error_widget.dart';

/// [VM] a view model extends [PaginationViewModel]
/// [T] the Model of item
class InfiniteScrollView<VM extends PaginationViewModel<T>, T extends Object> extends StatelessWidget {
  /// [viewModel] a class extends [PaginationViewModel]
  final VM viewModel;

  /// [itemBuilder] callback return [Widget] with item [T].
  final Widget Function(BuildContext context, int index, T item) itemBuilder;

  /// pass [topWidget] when you want to place a widget at the top of the first [itemBuilder] widget.
  final Widget? topWidget;

  /// [onRefresh] callback called when user swipe to refresh list.
  final Function()? onRefresh;

  /// [ScrollPhysics] of pagination scrollView.
  final ScrollPhysics? physics;

  /// [retry] callback called when pagination request faild and user press on [PaginationErrorWidget].
  final Function()? retry;

  /// warp [ScrollView] in [RefreshIndicator] when [refreshIndicator] == `true`
  ///
  /// default value is `true`
  final bool refreshIndicator;

  /// Scroll Direction default value is [Axis.vertical]
  final Axis scrollDirection;

  /// A delegate that controls the layout of the children within the [GridView].
  final SliverGridDelegate? gridDelegate;

  /// Whether to spawn a new isolate on which to calculate the diff on.
  final bool? spawnIsolate;

  /// scroll-view padding
  final EdgeInsets? padding;

  /// [noItemsWidget] is a widget appears after fetch first page data and the result is empty
  final Widget? noItemsWidget;

  /// [loadingWidget] is a widget appears when first page is in loading state.
  final Widget? loadingWidget;

  /// build [AnimatedInfiniteScrollView] with basic configuration
  const InfiniteScrollView({
    required this.viewModel,
    required this.itemBuilder,
    this.refreshIndicator = true,
    this.loadingWidget,
    this.onRefresh,
    this.topWidget,
    this.retry,
    this.physics,
    this.scrollDirection = Axis.vertical,
    this.gridDelegate,
    this.spawnIsolate,
    this.padding,
    this.noItemsWidget,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AnimatedInfiniteScrollView<T>(
      viewModel: viewModel,
      refreshIndicator: refreshIndicator,
      topWidget: topWidget,
      loadingWidget: loadingWidget ?? const CustomizedAnimatedWidget(child: Loader()),
      footerLoadingWidget: const PaginationLoaderWidget(),
      errorWidget: PaginationErrorWidget(
        retry: retry ?? () => viewModel.fetchData(viewModel.paginationParams.page),
      ),
      physics: physics ?? scrollPhysics,
      onRefresh: onRefresh,
      gridDelegate: gridDelegate,
      spawnIsolate: spawnIsolate,
      scrollDirection: scrollDirection,
      padding: padding,
      noItemsWidget: noItemsWidget,
      itemBuilder: itemBuilder,
    );
  }
}
