// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'register_request.freezed.dart';
part 'register_request.g.dart';

// ----------(json)----------
/*
{
  "name": "Test",
  "email": "test@mail.com",
  "password": "123456789",
  "country_code": "+1",
  "phone": "5555551234"
} 
*/
// --------------------------
@freezed
class RegisterRequest with _$RegisterRequest {
  const factory RegisterRequest({
    String? name,
    String? email,
    String? password,
    String? countryCode,
    String? phone,
  }) = _RegisterRequest;

  factory RegisterRequest.fromJson(Map<String, dynamic> json) => _$RegisterRequestFromJson(json);
}
