// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:isar/isar.dart';
import 'package:xflutter_cli_modules_application/common/data_source/local/isar.dart';
import 'package:xflutter_cli_modules_application/common/data_source/local/models/isar_models.dart';
import 'package:xflutter_cli_modules_application/common/models/models.dart';
import 'package:xflutter_cli_modules_application/core/utilities/di/di.dart';
import 'package:xflutter_cli_modules_application/common/environment/environment.dart';

class ProductLocalDataProvider {
  Isar get isar => findInstance<Isar>();

  /// [Product] query builder with pagination
  QueryBuilder<IsarProduct, IsarProduct, QAfterLimit> _productQueryBuilder({int? page}) {
    return isar.isarProducts
        .where()
        .sortById()
        .optional(page != null, (q) => q.offset(offset(page!, Environment.perPage)).limit(Environment.perPage));
  }

  /// find [Product] from local-database
  IsarProduct? findOne(int? id) {
    return isar.isarProducts.where().idEqualTo(id).findFirstSync();
  }

  /// fetch cached [Product] list from local-database
  List<IsarProduct> findAll({int? page}) {
    return _productQueryBuilder(page: page).findAllSync();
  }

  /// add/update [Product] into local-database
  void insert(Product data) {
    isar.writeTxnSync(() => isar.isarProducts.putByIdSync(data.toIsar()));
  }

  /// save list of [Product] in local-database
  void insertAll(List<Product> data, {int? page}) {
    // convert data to isar-entities
    final objects = data.map((e) => e.toIsar()).toList();

    // find old cached list
    final local = findAll(page: page).map((e) => e.id).toList();
    final ids = data.map((e) => e.id).toList();

    // find difference between old list and new list
    final difference = local.where((element) => !ids.contains(element)).toList();

    isar.writeTxnSync(() {
      // delete difference
      isar.isarProducts.deleteAllByIdSync(difference);

      // save new data
      isar.isarProducts.putAllByIdSync(objects);
    });
  }

  /// delete [Product] from local-database
  void delete(int? id) {
    isar.writeTxnSync(() => isar.isarProducts.deleteByIdSync(id));
  }

  /// count all documents in local-database
  int count() {
    return _productQueryBuilder().countSync();
  }
}
