// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../models.dart';

part 'blog.freezed.dart';
part 'blog.g.dart';

// ----------(json)----------
/*
{
  "_id": "66d0d872eef473aa268a2b32",
  "media": {
    "_id": "66d0d872eef473aa268a2b34",
    "path": "uploads/blogs/cc19e077-97c3-4f05-a845-212f1833f91a-1724962930172.png",
    "name": "Screenshot 2024-07-26 at 17.26.31.png",
    "mediaUrl": "http://localhost:3000",
    "fileType": {
      "ext": "png",
      "mime": "image/png"
    },
    "external": false,
    "createdAt": "2024-08-29T20:22:10.181Z"
  },
  "title": "Test Blog",
  "description": "the first test blog",
  "color": "#ff009d",
  "content": "<h1>Test Blog</h1><p><strong>test first blog</strong> d</p><p><a href=\"https://www.google.com/\" target=\"_blank\">Visit</a></p>",
  "archived": false,
  "views": 0,
  "keys": [
    "test"
  ],
  "id": "1ef66445-e8bb-6c40-a56b-49174f2356d5",
  "createdAt": "2024-08-29T20:22:10.181Z",
  "updatedAt": "2024-08-29T20:22:10.181Z"
} 
*/
// --------------------------
@freezed
class Blog with _$Blog {
  const factory Blog({
    @JsonKey(name: '_id') String? id,
    Media? media,
    String? title,
    String? description,
    String? color,
    String? content,
    bool? archived,
    int? views,
    List<String>? keys,
    String? mId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Blog;

  factory Blog.fromJson(Map<String, dynamic> json) => _$BlogFromJson(json);
}
