// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'dart:async';
import 'package:products/src/data/models/entities/product/product.dart';
import 'package:core/core.dart';

abstract class ProductsRepository {
  Future<BaseResponse<Product>> create(Product data);

  Future<BaseResponse<Product>> update(int? id, Product data);

  Stream<BaseResponse<ListResponse<Product>>> findAll(int page);

  Stream<BaseResponse<Product>> findOne(int? id, {bool withCache = true});

  Future<BaseResponse<dynamic>> delete(int? id);

  void dispose();
}
