// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:injectable/injectable.dart';
import 'products_repository.dart';
import 'package:products/src/data/models/entities/product/product.dart';
import 'package:products/src/data/data_sources/remote/products/products_remote_data_source.dart';
import 'package:core/core.dart';
import 'package:products/src/data/data_sources/local/products/products_local_data_source.dart';
import 'package:products/src/data/models/local/product/local_product.dart';
import 'package:products/src/data/data_sources/local/products/queries/local_products_query_parameters.dart';

@LazySingleton(scope: 'products', as: ProductsRepository)
class ProductsRepositoryImpl extends BaseRepository implements ProductsRepository {
  final ProductsRemoteDataSource _remoteDataSource;
  final ProductsLocalDataSource _localDataSource;

  ProductsRepositoryImpl(this._remoteDataSource, this._localDataSource);

  @override
  Future<BaseResponse<Product>> create(Product data) async {
    final cancelToken = CancelToken();
    // send request to create item
    final response = await getResponse<Product>(
      () => _remoteDataSource.create(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );

    if (response.data != null) {
      // save item in the cache
      try {
        _localDataSource.insert(LocalProduct.fromEntity(response.data!));
      } catch (error) {
        if (kDebugMode) print('ProductsRepository: $error');
      }
    }

    return response;
  }

  @override
  Future<BaseResponse<Product>> update(int? id, Product data) async {
    final cancelToken = CancelToken();
    // send request to update item
    final response = await getResponse<Product>(
      () => _remoteDataSource.update(id: id, data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );

    if (response.data != null) {
      // update item in the cache
      try {
        _localDataSource.insert(LocalProduct.fromEntity(response.data!));
      } catch (error) {
        if (kDebugMode) print('ProductsRepository: $error');
      }
    }

    return response;
  }

  @override
  Stream<BaseResponse<ListResponse<Product>>> findAll(int page, {String? query}) async* {
    final perPage = getIt<AppEnvironment>().perPage;

    // get cached data from local dataSource
    try {
      final cacheQueryParameters = LocalProductsListQueryParameters(page: page, perPage: perPage);
      final cached = await _localDataSource.findAll(cacheQueryParameters);
      if (cached.isNotEmpty) {
        final data = await compute((cached) => cached.map((e) => e.fromLocal()).toList(), cached);
        final total = isConnectingToInternet ? null : cached.length;
        // emit cached data
        yield BaseResponse(
          cached: true,
          success: true,
          data: ListResponse(total: total, cached: true, data: data),
        );
      } else if (!isConnectingToInternet) {
        yield BaseResponse(cached: false, success: true, data: ListResponse(total: 0, cached: false, data: []));
      }
    } catch (error) {
      if (kDebugMode) print('ProductsRepository: $error');
    }

    // check internet connection
    if (isConnectingToInternet) {
      // fetch data from server
      final cancelToken = CancelToken();
      final response = await getResponse<ListResponse<Product>>(
        () => _remoteDataSource.findAll(page: page, perPage: perPage, cancelToken: cancelToken),
        cancelToken: cancelToken,
      );

      // emit fetched data
      yield response;

      // insert fetched data into cache
      if (response.data?.data != null) {
        try {
          final data = await compute((data) => data.map((e) => LocalProduct.fromEntity(e)), response.data!.data!);
          await _localDataSource.insertAll(data);
        } catch (error) {
          if (kDebugMode) print('ProductsRepository: $error');
        }
      }
    }
  }

  @override
  Stream<BaseResponse<Product>> findOne(int? id, {bool withCache = true}) async* {
    if (withCache) {
      // get item from cache
      try {
        final cached = await _localDataSource.findOne(LocalProductQueryParameters(id: id));
        if (cached != null) {
          yield BaseResponse(success: true, data: cached.fromLocal(), cached: true);
        }
      } catch (error) {
        if (kDebugMode) print('ProductsRepository: $error');
      }
    }

    // check internet connection
    if (isConnectingToInternet) {
      // get item from remote server
      final cancelToken = CancelToken();
      final response = await getResponse<Product>(
        () => _remoteDataSource.findOne(id: id, cancelToken: cancelToken),
        cancelToken: cancelToken,
      );

      // emit fetched data
      yield response;

      // update cache with new fetched data
      if (response.data != null) {
        try {
          await _localDataSource.insert(LocalProduct.fromEntity(response.data!));
        } catch (error) {
          if (kDebugMode) print('ProductsRepository: $error');
        }
      }
    }
  }

  @override
  Future<BaseResponse<dynamic>> delete(int? id) async {
    final cancelToken = CancelToken();
    final response = await getResponse<dynamic>(
      () => _remoteDataSource.delete(id: id, cancelToken: cancelToken),
      cancelToken: cancelToken,
    );

    // remove item from cache
    if (response.isSuccess) {
      try {
        await _localDataSource.delete(id);
      } catch (error) {
        if (kDebugMode) print('ProductsRepository: $error');
      }
    }

    return response;
  }
}
