// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_test_application/ui/screens/products/widgets/product_list_widget.dart';
import '../viewmodels/products_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class ProductsMobileScreen extends StatelessWidget {
  const ProductsMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ProductsViewModel>(
      builder: (viewModel) => const ProductListWidget(),
    );
  }
}
