// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/data/models/entities/product/product.dart';
import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:xflutter_cli_test_application/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_test_application/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_test_application/ui/widgets/text_fields/customized_reactive_text_field.dart';

class ProductForm extends StatefulWidget {
  final Product? product;
  final Function(Map<String, dynamic> value) submit;

  const ProductForm({this.product, required this.submit, super.key});

  @override
  State<ProductForm> createState() => _ProductFormState();
}

class _ProductFormState extends State<ProductForm> {
  late final productForm = FormGroup({
    'title': FormControl<String>(validators: [Validators.required]),
    'description': FormControl<String>(validators: [Validators.required]),
    'category': FormControl<String>(validators: [Validators.required]),
    'price': FormControl<double>(validators: [Validators.required]),
    'discountPercentage': FormControl<double>(validators: [Validators.required]),
    'rating': FormControl<double>(validators: [Validators.required]),
    'stock': FormControl<int>(validators: [Validators.required]),
    'brand': FormControl<String>(validators: [Validators.required]),
    'sku': FormControl<String>(validators: [Validators.required]),
    'weight': FormControl<int>(validators: [Validators.required]),
    'warrantyInformation': FormControl<String>(validators: [Validators.required]),
    'shippingInformation': FormControl<String>(validators: [Validators.required]),
    'availabilityStatus': FormControl<String>(validators: [Validators.required]),
    'returnPolicy': FormControl<String>(validators: [Validators.required]),
    'minimumOrderQuantity': FormControl<int>(validators: [Validators.required]),
    'thumbnail': FormControl<String>(validators: [Validators.required]),
  });

  @override
  void initState() {
    super.initState();
    updateFormValue(widget.product);
  }

  @override
  void didUpdateWidget(covariant ProductForm oldWidget) {
    if (oldWidget.product != widget.product) {
      // update form inputs with new product data
      updateFormValue(widget.product);
    }
    super.didUpdateWidget(oldWidget);
  }

  /// update form fields with [product] value
  void updateFormValue(Product? product) {
    if (widget.product != null) {
      productForm.patchValue(product!.toJson());
    }
  }

  @override
  Widget build(BuildContext context) {
    final formGroup = productForm;

    return ReactiveForm(
      formGroup: formGroup,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          // form fields
          Column(
            children: [
              // title
              CustomizedReactiveFormField<String>(
                key: const Key('title'),
                formControlName: 'title',
                labelText: 'title'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('description'),
              ),
              const SizedBox(height: formSpacing),

              // description
              CustomizedReactiveFormField<String>(
                key: const Key('description'),
                formControlName: 'description',
                labelText: 'description'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('category'),
              ),
              const SizedBox(height: formSpacing),

              // category
              CustomizedReactiveFormField<String>(
                key: const Key('category'),
                formControlName: 'category',
                labelText: 'category'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('price'),
              ),
              const SizedBox(height: formSpacing),

              // price
              CustomizedReactiveFormField<double>(
                key: const Key('price'),
                formControlName: 'price',
                labelText: 'price'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('discountPercentage'),
              ),
              const SizedBox(height: formSpacing),

              // discountPercentage
              CustomizedReactiveFormField<double>(
                key: const Key('discountPercentage'),
                formControlName: 'discountPercentage',
                labelText: 'discountPercentage'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('rating'),
              ),
              const SizedBox(height: formSpacing),

              // rating
              CustomizedReactiveFormField<double>(
                key: const Key('rating'),
                formControlName: 'rating',
                labelText: 'rating'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('stock'),
              ),
              const SizedBox(height: formSpacing),

              // stock
              CustomizedReactiveFormField<int>(
                key: const Key('stock'),
                formControlName: 'stock',
                labelText: 'stock'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('brand'),
              ),
              const SizedBox(height: formSpacing),

              // brand
              CustomizedReactiveFormField<String>(
                key: const Key('brand'),
                formControlName: 'brand',
                labelText: 'brand'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('sku'),
              ),
              const SizedBox(height: formSpacing),

              // sku
              CustomizedReactiveFormField<String>(
                key: const Key('sku'),
                formControlName: 'sku',
                labelText: 'sku'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('weight'),
              ),
              const SizedBox(height: formSpacing),

              // weight
              CustomizedReactiveFormField<int>(
                key: const Key('weight'),
                formControlName: 'weight',
                labelText: 'weight'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('warrantyInformation'),
              ),
              const SizedBox(height: formSpacing),

              // warrantyInformation
              CustomizedReactiveFormField<String>(
                key: const Key('warrantyInformation'),
                formControlName: 'warrantyInformation',
                labelText: 'warrantyInformation'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('shippingInformation'),
              ),
              const SizedBox(height: formSpacing),

              // shippingInformation
              CustomizedReactiveFormField<String>(
                key: const Key('shippingInformation'),
                formControlName: 'shippingInformation',
                labelText: 'shippingInformation'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('availabilityStatus'),
              ),
              const SizedBox(height: formSpacing),

              // availabilityStatus
              CustomizedReactiveFormField<String>(
                key: const Key('availabilityStatus'),
                formControlName: 'availabilityStatus',
                labelText: 'availabilityStatus'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('returnPolicy'),
              ),
              const SizedBox(height: formSpacing),

              // returnPolicy
              CustomizedReactiveFormField<String>(
                key: const Key('returnPolicy'),
                formControlName: 'returnPolicy',
                labelText: 'returnPolicy'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('minimumOrderQuantity'),
              ),
              const SizedBox(height: formSpacing),

              // minimumOrderQuantity
              CustomizedReactiveFormField<int>(
                key: const Key('minimumOrderQuantity'),
                formControlName: 'minimumOrderQuantity',
                labelText: 'minimumOrderQuantity'.tr(),
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                onSubmitted: (_) => formGroup.focus('thumbnail'),
              ),
              const SizedBox(height: formSpacing),

              // thumbnail
              CustomizedReactiveFormField<String>(
                key: const Key('thumbnail'),
                formControlName: 'thumbnail',
                labelText: 'thumbnail'.tr(),
                keyboardType: TextInputType.text,
                textInputAction: TextInputAction.done,
                onSubmitted: (_) {},
              ),
              const SizedBox(height: formSpacing),
            ],
          ),

          // submit widget
          SizedBox(
            width: double.infinity,
            child: CustomizedButton(
              key: const Key('submit'),
              child: Text('next'.tr()),
              callback: () {
                if (formGroup.valid) {
                  widget.submit(formGroup.value);
                } else {
                  formGroup.markAllAsTouched();
                }
              },
            ),
          ),
        ],
      ),
    );
  }
}
