// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'product_card_widget.dart';
import 'product_redacted_widget.dart';
import 'package:xflutter_cli_test_application/models/models.dart';
import '../viewmodels/products_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';
import 'package:xflutter_cli_test_application/ui/widgets/infinite_scroll_view/infinite_scroll_view.dart';

class ProductListWidget extends StatelessWidget {
  const ProductListWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ProductsViewModel>(
      builder: (viewModel) => InfiniteScrollView<ProductsViewModel, Product>(
        viewModel: viewModel,
        loadingWidget: const ProductRedactedWidget(),
        itemBuilder: (context, index, item) => ProductCardWidget(item),
      ),
    );
  }
}
