name: theme
version: 0.0.1
homepage: none
publish_to: none
description: generate main colors & themes
environment: 
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  shared_preferences: ^2.0.15
  flutterx_live_data: ^1.9.2
  utilities: 
    path: ../../packages/utilities
  events: 
    path: ../../packages/events
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: null
