// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';
part 'reset_password_request.freezed.dart';
part 'reset_password_request.g.dart';

/// **************************************************************************
/// IMPORTANT: keep [ResetPasswordRequest] class definition at the top in this file,
/// if you want to add some extensions or extra classes, declare these definitions at the bottom
/// **************************************************************************
@freezed
abstract class ResetPasswordRequest with _$ResetPasswordRequest {
  const factory ResetPasswordRequest({
    @JsonKey(name: 'email') String? email,
    @JsonKey(name: 'reset_password_code') String? resetPasswordCode,
    @JsonKey(name: 'new_password') String? newPassword,
  }) = _ResetPasswordRequest;

  factory ResetPasswordRequest.fromJson(Map<String, dynamic> json) => _$ResetPasswordRequestFromJson(json);
}
