// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:customer_app/common/router/app_router.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import './viewmodels/forget_password_viewmodel.dart';
import 'package:core/core.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:auto_route/auto_route.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'mobile/forget_password_mobile_screen.dart';
import 'tablet/forget_password_tablet_screen.dart';

@RoutePage(name: 'forgetPassword')
class ForgetPasswordScreen extends StatefulWidget {
  const ForgetPasswordScreen({super.key});

  @override
  State<ForgetPasswordScreen> createState() => _ForgetPasswordScreenState();
}

class _ForgetPasswordScreenState extends State<ForgetPasswordScreen> with InstanceState<ForgetPasswordScreen, ForgetPasswordViewModel>, ObserverMixin {
  void observeEvents() {
    viewModel.eventEmitter.observe((value) {
      if (value != null) {
        final email = viewModel.params.forgetPasswordForm.controls['email']?.value.toString() ?? '';
        appRouter.push(VerifyPinCode(
          email: email,
          pageRoute: const ResetPassword(),
        ));
      }
    });
  }

  @override
  void onInitState() {
    super.onInitState();
    observeEvents();
  }

  @override
  Widget screen(context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => BaseAppBar(title: 'forget_password'.tr()),
          builder: (context, theme) => SafeArea(
            child: ScreenTypeLayout.builder(
              mobile: (context) => const ForgetPasswordMobileScreen(),
              tablet: (context) => const ForgetPasswordTabletScreen(),
            ),
          ),
        ),
        LiveDataFullScreenLoader(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  ForgetPasswordViewModel registerInstance() => ForgetPasswordViewModel();
}
