/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'register_params.dart';
import 'package:xflutter_cli_test_application/viewmodels/base_viewmodel.dart';

class RegisterViewModel extends BaseViewModel {
  late final params = RegisterParams();
      
  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    super.onDispose();
  }
}