name: models
version: 0.0.1
homepage: none
publish_to: none
description: generate core models like `BaseResponse` and generic `Result`
environment: 
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: null
