import 'package:xflutter_cli_test_application/ui/screens/register/register_screen.dart';
import 'package:xflutter_cli_test_application/ui/screens/home/home_screen.dart';

/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:auto_route/auto_route.dart';

part 'app_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Screen')
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(
          path: '/register',
          page: Register.page,
        ),
        AutoRoute(
          path: '/home',
          page: Home.page,
          initial: true,
        ),
      ];
}

final appRouter = AppRouter();
