// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/ui/screens/authentication/verify_pin_code/verify_pin_code_screen.dart';
import 'package:flutter/material.dart';
import 'package:xflutter_cli_test_application/ui/screens/authentication/login/login_screen.dart';
import 'package:xflutter_cli_test_application/ui/screens/home/home_screen.dart';
import 'package:auto_route/auto_route.dart';
part 'app_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Screen')
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(
          path: '/verify_pin_code',
          page: VerifyPinCode.page,
          initial: true,
        ),
        AutoRoute(
          path: '/login',
          page: Login.page,
        ),
        AutoRoute(
          path: '/home',
          page: Home.page,
        ),
      ];
}

final appRouter = AppRouter();

extension RouterUtils on AppRouter {
  /// push if the current route is not equal to [route],
  /// back to [route] if exists in [appRouter].[stack]
  Future<dynamic> pushToStack(PageRouteInfo route) async {
    if (appRouter.stack.map((e) => e.name).contains(route.routeName)) {
      // check if route exists in stack
      // back to route instead of duplicate same route
      return appRouter.popUntilRouteWithName(route.routeName);
    } else if (appRouter.current.name != route.routeName) {
      // push route
      return appRouter.push(route);
    }
  }
}
