// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';
import 'package:products/products.dart';

@RoutePage(name: 'customerProducts')
class CustomerProductsScreen extends StatefulWidget {
  const CustomerProductsScreen({super.key});

  @override
  State<CustomerProductsScreen> createState() => _CustomerProductsScreenState();
}

class _CustomerProductsScreenState extends State<CustomerProductsScreen> {
  @override
  Widget build(BuildContext context) {
    return const ProductsScreen();
  }
}
