// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_modules_application/modules/products/data_source/paging/product_paging_data_source.dart';
import 'products_params.dart';
import 'package:xflutter_cli_modules_application/common/viewmodels/base_viewmodel.dart';

class ProductsViewModel extends BaseViewModel {
  late final productsPagingDataSource = ProductsPagingDataSource();

  late final params = ProductsParams();
  @override
  void onReady() {
    super.onReady();
    productsPagingDataSource.fetchNewChunk();
  }

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    productsPagingDataSource.dispose();
    super.onDispose();
  }
}
