name: test_package
version: 0.0.1
homepage: none
publish_to: none
description: Test_package Package
environment: 
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: null
