targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          ignore_unannotated: false
          include_if_null: true
          generic_argument_factories: true
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/**_screen.dart
      injectable_generator:injectable_builder:  
        options:  
          auto_register: true
          file_name_pattern: "_module$"