// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:objectbox/objectbox.dart';
import 'package:products/src/data/models/entities/product/product.dart';
import 'package:products/src/data/models/local/dimensions/local_dimensions.dart';
import 'package:products/src/data/models/local/review/local_review.dart';
import 'package:products/src/data/models/local/meta/local_meta.dart';

@Entity()
class LocalProduct {
  @Id(assignable: true)
  int id;
  String? title;
  String? description;
  String? category;
  double? price;
  double? discountPercentage;
  double? rating;
  int? stock;
  List<String>? tags;
  String? brand;
  String? sku;
  int? weight;
  final toOneDimensions = ToOne<LocalDimensions>();
  String? warrantyInformation;
  String? shippingInformation;
  String? availabilityStatus;
  final toManyReviews = ToMany<LocalReview>();
  String? returnPolicy;
  int? minimumOrderQuantity;
  final toOneMeta = ToOne<LocalMeta>();
  List<String>? images;
  String? thumbnail;
  @Transient()
  LocalDimensions? dimensions;
  @Transient()
  List<LocalReview>? reviews;
  @Transient()
  LocalMeta? meta;

  LocalProduct({
    required this.id,
    this.title,
    this.description,
    this.category,
    this.price,
    this.discountPercentage,
    this.rating,
    this.stock,
    this.tags,
    this.brand,
    this.sku,
    this.weight,
    this.warrantyInformation,
    this.shippingInformation,
    this.availabilityStatus,
    this.returnPolicy,
    this.minimumOrderQuantity,
    this.images,
    this.thumbnail,
  });

  /// convert [Product] to [LocalProduct]
  factory LocalProduct.fromEntity(Product entity) {
    final item = LocalProduct(
      id: entity.id ?? 0,
      title: entity.title,
      description: entity.description,
      category: entity.category,
      price: entity.price?.toDouble(),
      discountPercentage: entity.discountPercentage?.toDouble(),
      rating: entity.rating?.toDouble(),
      stock: entity.stock,
      tags: entity.tags,
      brand: entity.brand,
      sku: entity.sku,
      weight: entity.weight,
      warrantyInformation: entity.warrantyInformation,
      shippingInformation: entity.shippingInformation,
      availabilityStatus: entity.availabilityStatus,
      returnPolicy: entity.returnPolicy,
      minimumOrderQuantity: entity.minimumOrderQuantity,
      images: entity.images,
      thumbnail: entity.thumbnail,
    );

    if (entity.dimensions != null) {
      item.toOneDimensions.target = LocalDimensions.fromEntity(entity.dimensions!);
    }
    if (entity.meta != null) {
      item.toOneMeta.target = LocalMeta.fromEntity(entity.meta!);
    }

    if (entity.reviews != null) {
      item.toManyReviews.addAll(entity.reviews?.map((e) => LocalReview.fromEntity(e)) ?? []);
    }

    return item;
  }

  /// convert [LocalProduct] to [Product]
  Product fromLocal() => Product(
    id: id,
    title: title,
    description: description,
    category: category,
    price: price,
    discountPercentage: discountPercentage,
    rating: rating,
    stock: stock,
    tags: tags,
    brand: brand,
    sku: sku,
    weight: weight,
    warrantyInformation: warrantyInformation,
    shippingInformation: shippingInformation,
    availabilityStatus: availabilityStatus,
    returnPolicy: returnPolicy,
    minimumOrderQuantity: minimumOrderQuantity,
    images: images,
    thumbnail: thumbnail,

    dimensions: toOneDimensions.target?.fromLocal(),
    meta: toOneMeta.target?.fromLocal(),
    reviews: toManyReviews.map((e) => e.fromLocal()).toList(),
  );
}
