// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:products/src/ui/screens/products/widgets/product_form.dart';
import 'package:flutter/material.dart';
import '../viewmodels/update_product_viewmodel.dart';
import 'package:core/core.dart';

class UpdateProductMobileScreen extends StatelessWidget {
  const UpdateProductMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<UpdateProductViewModel>(
      builder: (UpdateProductViewModel viewModel) {
        return BaseScrollView(
          padding: adaptivePadding,
          child: ProductForm(product: viewModel.params.product.value.dataOrNull, submit: viewModel.submit),
        );
      },
    );
  }
}
