name: orders
version: 0.0.1
homepage: none
publish_to: none
description: Orders Package
environment: 
  sdk: ^3.5.1
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
