// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'product_card_widget.dart';
import 'product_redacted_widget.dart';
import 'package:core/core.dart';
import 'package:products/src/mediators/paging/products_paging_controller.dart';
import 'package:products/src/data/models/entities/product/product.dart';

class ProductsListWidget extends StatelessWidget {
  final ProductsPagingController controller;
  const ProductsListWidget({required this.controller, super.key});

  @override
  Widget build(BuildContext context) {
    return InfiniteScrollView<Product, ProductsPagingController>(
      controller: controller,
      loadingWidget: const ProductRedactedWidget(),
      itemBuilder: (BuildContext context, Product item, int index) => ProductCardWidget(
        item,
      ),
    );
  }
}
