// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:products/src/data/models/entities/product/product.dart';

class ProductCardWidget extends StatelessWidget {
  final Product product;
  const ProductCardWidget(this.product, {super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      padding: const EdgeInsets.all(10),
      child: Row(
        children: [
          // product image
          if (product.thumbnail != null)
            Image.network(
              product.thumbnail!,
              width: 100,
              height: 100,
            ),

          // product title
          Text(product.title ?? ''),
        ],
      ),
    );
  }
}
