// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';
import 'dart:async';
import 'package:xflutter_cli_test_application/data_source/repositories/base_repository.dart';
import 'package:xflutter_cli_test_application/models/models.dart';
import 'package:xflutter_cli_test_application/utilities/dependencies/dependencies_management.dart';
import 'package:xflutter_cli_test_application/data_source/remote/authentication_rest_client/authentication_rest_client.dart';

class AuthenticationRepository extends BaseRepository {
  late final restClient = AuthenticationRestClient(findInstance<Dio>());

  Future<BaseResponse<dynamic>> login(LoginRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.login(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> verifyPinCode(VerifyCodeRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.verifyPinCode(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> resendVerificationCode(GetVerificationCodeRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.resendVerificationCode(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> register(RegisterRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.register(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> forgetPassword(GetVerificationCodeRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.forgetPassword(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> resetPassword(ResetPasswordRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.resetPassword(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }

  Future<BaseResponse<dynamic>> changePassword(ChangePasswordRequest data) {
    final cancelToken = CancelToken();
    return getResponse(
      () => restClient.changePassword(data: data.toJson(), cancelToken: cancelToken),
      cancelToken: cancelToken,
    );
  }
}
