// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/mediators/paging/products_paging_controller.dart';
import 'package:injectable/injectable.dart';
import 'home_params.dart';
import 'package:xflutter_cli_test_application/viewmodels/base_viewmodel.dart';

@LazySingleton(scope: 'home')
class HomeViewModel extends BaseViewModel {
  final params = HomeParams();
  final ProductsPagingController _productsPagingController;

  HomeViewModel(this._productsPagingController);

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onReady() {
    super.onReady();
    // fetch first products chuck.
    _productsPagingController.fetchNewChunk();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    _productsPagingController.dispose();
    super.onDispose();
  }
}
