// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'home_params.dart';
import 'package:xflutter_cli_test_application/viewmodels/base_viewmodel.dart';

class HomeViewModel extends BaseViewModel {
  late final params = HomeParams();

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    super.onDispose();
  }
}
