/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import '../widgets/product_list_widget.dart';
import '../viewmodels/products_viewmodel.dart';
import 'package:core/core.dart';

class ProductsMobileScreen extends StatelessWidget {
  const ProductsMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ProductsViewModel>(
      builder: (viewModel) => const ProductListWidget(),
    );
  }
}
