// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:products/src/data/models/entities/product/product.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import './viewmodels/update_product_viewmodel.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'mobile/update_product_mobile_screen.dart';
import 'package:core/core.dart';
import 'package:products/src/di/products_injectable.config.dart';

class UpdateProductScreen extends StatefulWidget {
  final int id;

  const UpdateProductScreen({required this.id, super.key});

  @override
  State<UpdateProductScreen> createState() => _UpdateProductScreenState();
}

class _UpdateProductScreenState extends State<UpdateProductScreen>
    with LifecycleOwner<UpdateProductScreen, UpdateProductViewModel>, ObserverMixin {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // screen body
        BaseScaffold(
          appBar: (context, theme) => BaseAppBar(title: 'update_product'.tr()),
          builder: (context, theme) => SafeArea(
            child: LiveDataBuilder<Result<Product>>(
              data: viewModel.params.product,
              builder: (BuildContext context, Result<Product> value) {
                return value.when(
                  idle: () => const SizedBox(),
                  loading: () => const Center(child: CircularProgressIndicator.adaptive()),
                  data: (_) => ScreenTypeLayout.builder(mobile: (_) => UpdateProductMobileScreen()),
                  error: (message, _, _) => Center(child: Text(message)),
                );
              },
            ),
          ),
        ),
      ],
    );
  }

  @override
  void onInitState() {
    viewModel.params.id = widget.id;
    super.onInitState();
  }

  @override
  DiScope get diScope => DiScope(name: 'updateProduct', factory: getIt.initUpdateProductScope, dependencies: []);
}
