// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/foundation.dart';
import 'package:injectable/injectable.dart';
import 'queries/local_categories_query_parameters.dart';
import 'categories_local_data_source.dart';
import 'package:xflutter_cli_test_application/data/database/app_store.dart';
import 'package:xflutter_cli_test_application/data/models/local/category/local_category.dart';
import 'package:xflutter_cli_test_application/data/database/objectbox.g.dart';

@Injectable(as: CategoriesLocalDataSource)
class CategoriesLocalDataSourceImpl implements CategoriesLocalDataSource {
  final ObjectBoxAppStore _appStore;
  CategoriesLocalDataSourceImpl(this._appStore);

  @override
  Future<void> insert(LocalCategory data) => insertAll([data]);

  @override
  Future<void> insertAll(Iterable<LocalCategory> data) async {
    return _appStore.executeWithStore<void>(
      (store) => store.runInTransactionAsync<void, List<LocalCategory>>(TxMode.write, (Store store, List<LocalCategory> parameter) {
        try {
          final box = store.box<LocalCategory>();

          // insert new data, and update existing data
          box.putMany(parameter);
        } catch (error) {
          if (kDebugMode) print('CategoriesLocalDataSource: $error');
        }
      }, data.toList()),
    );
  }

  @override
  Future<LocalCategory?> findOne(LocalCategoryQueryParameters queryParameters) async {
    if (queryParameters.id == null) return null;
    return _appStore.executeWithStore<LocalCategory?>(
      (store) async => store.runInTransaction<LocalCategory?>(TxMode.read, () {
        try {
          final box = store.box<LocalCategory>();

          Condition<LocalCategory>? conditions;
          if (queryParameters.id != null) {
            // filter on id
            final idCondition = LocalCategory_.id.equals(queryParameters.id!);
            conditions = idCondition;
          }

          // query for find item with filter conditions
          final query = box.query(conditions);

          final builder = query.build();

          // fetch item
          final item = builder.findFirst();

          // clean up resources
          builder.close();

          return item;
        } catch (error) {
          if (kDebugMode) print('CategoriesLocalDataSource: $error');
          return null;
        }
      }),
    );
  }

  @override
  Future<List<LocalCategory>> findAll(LocalCategoriesListQueryParameters queryParameters) async {
    return _appStore.executeWithStore<List<LocalCategory>>(
      (store) async => store.runInTransaction<List<LocalCategory>>(TxMode.read, () {
        try {
          final box = store.box<LocalCategory>();
          final query = box.query();
          final builder = query.build();

          // fetch data with pagination
          final page = queryParameters.page;
          final perPage = queryParameters.perPage;
          if (page != null && perPage != null) {
            builder.offset = (perPage * page) - perPage;
            builder.limit = perPage;
          }

          // fetch items
          final items = builder.find();

          // clean up resources
          builder.close();

          return items;
        } catch (error) {
          if (kDebugMode) print('CategoriesLocalDataSource: $error');
          return [];
        }
      }),
    );
  }

  @override
  Future<int> delete(int? id) async {
    if (id == null) return 0;
    return _appStore.executeWithStore<int>(
      (store) => store.runInTransactionAsync<int, int>(TxMode.write, (Store store, int parameter) {
        try {
          final box = store.box<LocalCategory>();
          // filter item
          final builder = box.query(LocalCategory_.id.equals(id)).build();

          // remove item
          final result = builder.remove();

          // clean up resources
          builder.close();

          return result;
        } catch (error) {
          if (kDebugMode) print('CategoriesLocalDataSource: $error');
          return 0;
        }
      }, id),
    );
  }

  @override
  Future<int> count() async {
    return _appStore.executeWithStore<int>(
      (store) async => store.runInTransaction<int>(TxMode.read, () {
        try {
          final box = store.box<LocalCategory>();
          final query = box.query();
          final builder = query.build();

          // count items
          final count = builder.count();

          // clean up resources
          builder.close();

          return count;
        } catch (error) {
          if (kDebugMode) print('CategoriesLocalDataSource: $error');
          return 0;
        }
      }),
    );
  }
}
