// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'queries/local_categories_query_parameters.dart';
import 'package:xflutter_cli_test_application/data/models/local/category/local_category.dart';

abstract class CategoriesLocalDataSource {
  /// find [LocalCategory] from local-database
  Future<LocalCategory?> findOne(LocalCategoryQueryParameters queryParameters);

  /// fetch cached [LocalCategory] list from local-database
  Future<List<LocalCategory>> findAll(LocalCategoriesListQueryParameters queryParameters);

  /// add/update [LocalCategory] into local-database
  Future<void> insert(LocalCategory data);

  /// save list of [LocalCategory] in local-database
  Future<void> insertAll(Iterable<LocalCategory> data);

  /// delete [LocalCategory] from local-database
  Future<int> delete(int? id);

  /// count all [LocalCategory] items in local-database
  Future<int> count();
}
