# melos is a tool for managing Dart projects with multiple packages.
# https://melos.invertase.dev
name: test_workspace

packages:
  - apps/*
  - packages/*

scripts:
  analyze:
    exec: dart analyze .