// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:redacted/redacted.dart';
import 'package:products/products.dart';

class ProductRedactedWidget extends StatelessWidget {
  final int itemCount;
  const ProductRedactedWidget({this.itemCount = 4, super.key});

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: itemCount,
      itemBuilder: (context, index) => ProductCardWidget(
        Product(
          thumbnail: "https://placehold.co/600x400.png",
          title: "Product",
        ),
      ).redacted(
        context: context,
        redact: true,
      ),
    );
  }
}
