// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:redacted/redacted.dart';
import '../../../../models/models.dart';
import 'product_card_widget.dart';

class ProductRedactedWidget extends StatelessWidget {
  final int itemCount;
  const ProductRedactedWidget({this.itemCount = 4, super.key});

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: itemCount,
      itemBuilder: (context, index) => const ProductCardWidget(
        Product(
          title: "Product",
          thumbnail: "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
        ),
      ).redacted(context: context, redact: true),
    );
  }
}
