// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/data/models/entities/product/product.dart';
import 'package:xflutter_cli_test_application/extensions/live_data_extension.dart';

class UpdateProductParams {
  late int id;
  final product = const Product().liveResult;
}
