// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:customer_app/common/models/models.dart';

part 'authentication_rest_client.g.dart';

@RestApi()
abstract class AuthenticationRestClient {
  factory AuthenticationRestClient(Dio dio) = _AuthenticationRestClient;

  @POST("/auth/login")
  Future<BaseResponse<dynamic>> login({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/auth/verify")
  Future<BaseResponse<dynamic>> verifyPinCode({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/auth/resend-code")
  Future<BaseResponse<dynamic>> resendVerificationCode({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });
  @POST("/auth/register")
  Future<BaseResponse<dynamic>> register({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/auth/forget-password")
  Future<BaseResponse<dynamic>> forgetPassword({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/auth/reset-password")
  Future<BaseResponse<dynamic>> resetPassword({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });

  @POST("/auth/change-password")
  Future<BaseResponse<dynamic>> changePassword({
    @Body() required Map<String, dynamic> data,
    @CancelRequest() CancelToken? cancelToken,
  });
}
