name: extensions
version: 0.0.1
homepage: none
publish_to: none
description: generate extensions to add some functionality to existing libraries
environment: 
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutterx_live_data: ^1.9.2
  utilities: 
    path: ../../packages/utilities
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: null
