// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';
import 'package:pretty_dio_logger/pretty_dio_logger.dart';
import 'package:flutter/foundation.dart';
import 'http_interceptor.dart';
import 'package:xflutter_cli_modules_application/core/utilities/di/di.dart';

class AppHttpClient {
  /// register global instance from [Dio]
  static void initialize() {
    _httpClientConfig();
  }

  static void _httpClientConfig() {
    final dio = Dio()
      ..transformer = BackgroundTransformer()
      ..interceptors.addAll([HttpInterceptor()]);

    if (kDebugMode) {
      final logger = PrettyDioLogger(
        request: true,
        compact: true,
        error: true,
        requestBody: true,
        requestHeader: true,
        responseBody: true,
        responseHeader: true,
      );
      // add logger in debug mode
      dio.interceptors.add(logger);
    }

    putInstance<Dio>(dio);
  }
}
