// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppStorage {
  /// get global instance from [SharedPreferences]
  static SharedPreferences get _preferences => GetIt.instance.get<SharedPreferences>();
}
