// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';

class AppTextButton extends StatelessWidget {
  final String text;
  final Function() callback;
  final TextStyle? textStyle;
  final bool enabled;

  const AppTextButton({
    required this.text,
    required this.callback,
    this.textStyle,
    this.enabled = true,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final buttonStyle = Theme.of(context).textButtonTheme.style;
    final style = textStyle ?? buttonStyle?.textStyle?.resolve(enabled ? {} : {WidgetState.disabled});
    return TextButton(
      onPressed: !enabled ? null : callback,
      child: Text(text, style: style),
    );
  }
}
