// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'dart:async';
import 'base_params.dart';
import 'package:core/src/data/models/ui_models/ui_message/ui_message.dart';
import 'package:core/src/data/models/responses/base_response/base_response.dart';

abstract class BaseViewModel extends LifeCycle {
  final baseParams = BaseParams();

  /// handle calling http request
  ///
  /// [setLoading] is optional [Function] which control your ui-loader while request in-progress.
  ///
  /// [request] is a [Future] return type of [BaseResponse] called inside [callHttpRequest].
  ///
  /// [callback] is a [Function] called after [request] fetched, it returns nullable [X] result if [request] success else return `null`.
  ///
  /// [onResponse] return the [BaseResponse] which give you more control for handling.
  Future<void> callHttpRequest<X>(
    Future<BaseResponse<X>> Function() request, {
    bool showErrorMessage = true,
    void Function(bool value)? setLoading,
    void Function(X? result, bool success)? callback,
    void Function(BaseResponse<X> response)? onResponse,
  }) async {
    // notify ui to show loader
    setLoading?.call(true);

    // call http request
    final response = await request.call();
    if (response.isSuccess) {
      // success response
      callback?.call(response.data, true);
    } else {
      // error response
      if (showErrorMessage) {
        showUiMessage(
          uiMessage: UiMessage(message: response.message, state: UiMessageState.error),
        );
      }
      callback?.call(null, false);
    }
    setLoading?.call(false);
    onResponse?.call(response);
  }

  /// call http request with stream, this function used if your repository fetch data from multiple data-source (local and remote)
  ///
  /// [setLoading] is optional [Function] which control your ui-loader while request in-progress.
  ///
  /// [request] is a [Future] return type of [BaseResponse] called inside [callStreamRequest].
  ///
  /// [callback] is a [Function] called after [request] fetched, it returns nullable [X] result if [request] success else return `null`.
  ///
  /// [onResponse] return the [BaseResponse] which give you more control for handling.
  Future<void> callStreamRequest<X>(
    Stream<BaseResponse<X>> Function() request, {
    void Function(bool value)? setLoading,
    void Function(X? result, bool success)? callback,
    void Function(BaseResponse<X> response)? onResponse,
  }) async {
    // notify ui to show loader
    setLoading?.call(true);

    await for (final response in request.call()) {
      if (response.success == true) {
        setLoading?.call(false);
        // success response
        callback?.call(response.data, true);
      } else {
        setLoading?.call(false);
        // error response
        showUiMessage(
          uiMessage: UiMessage(message: response.message, state: UiMessageState.error),
        );
        callback?.call(null, false);
      }
      onResponse?.call(response);
    }
  }

  /// show message through snackbar
  void showUiMessage({required UiMessage uiMessage}) {
    baseParams.emitUiMessage(uiMessage);
  }
}

/// Controlled from [LifecycleOwner] widget
abstract class LifeCycle {
  /// Called immediately after the widget is allocated in memory.
  void onInit() {}

  /// Called 1 frame after onInit().
  void onReady() {}

  /// Called immediately before the widget is disposed.
  void onDispose() {}
}
