// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_modules_application/core/events/event_bus.dart';
import 'package:xflutter_cli_modules_application/modules/authentication/data/repositories/authentication/authentication_repository.dart';
import 'package:xflutter_cli_modules_application/modules/authentication/data/models/requests/reset_password_request/reset_password_request.dart';
import 'package:injectable/injectable.dart';
import 'reset_password_params.dart';
import 'package:xflutter_cli_modules_application/common/viewmodels/base_viewmodel.dart';

@LazySingleton(scope: 'resetPassword')
class ResetPasswordViewModel extends BaseViewModel {
  final params = ResetPasswordParams();
  final AuthenticationRepository _authenticationRepository;
  ResetPasswordViewModel(this._authenticationRepository);

  @override
  void onInit() {
    // called immediately after the widget is allocated in memory.
    super.onInit();
  }

  @override
  void onDispose() {
    // called immediately before the widget is disposed
    _authenticationRepository.dispose();
    super.onDispose();
  }

  void submit() {
    eventBus.fire(const SoftKeyboardEvent());
    final request = ResetPasswordRequest.fromJson(params.resetPasswordForm.value);
    callHttpRequest(
      () => _authenticationRepository.resetPassword(request),
      setLoading: baseParams.setLoading,
      callback: (result, success) {
        if (result != null && success) {
          params.setResult(result!);
        }
      },
    );
  }
}
