// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'interaction_widget.dart';

class AnimatedGesture extends StatefulWidget {
  final Widget child;
  final Function() callback;
  final double? fadeValue;
  final double? scaleValue;
  final AnimationType? animationType;
  final bool enabled;
  const AnimatedGesture({
    required this.child,
    required this.callback,
    this.enabled = true,
    this.fadeValue,
    this.scaleValue,
    this.animationType,
    super.key,
  });

  @override
  State<AnimatedGesture> createState() => _AnimatedGestureState();
}

class _AnimatedGestureState extends State<AnimatedGesture> {
  final GlobalKey<InteractionWidgetState> globalKey = GlobalKey<InteractionWidgetState>();
  @override
  Widget build(BuildContext context) {
    return InteractionWidget(
      key: globalKey,
      fadeValue: widget.fadeValue,
      scaleValue: widget.scaleValue,
      type: widget.animationType ?? AnimationType.fadeScale,
      child: InkWell(
        highlightColor: Colors.transparent,
        splashColor: Colors.transparent,
        focusColor: Colors.transparent,
        hoverColor: Colors.transparent,
        onTap: () {
          if (widget.enabled) globalKey.currentState?.animate(callback: widget.callback);
        },
        child: widget.child,
      ),
    );
  }
}
