// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';
part 'media.freezed.dart';
part 'media.g.dart';

@freezed
class Media with _$Media {
  const factory Media({
    @JsonKey(name: 'id') int? id,
    @JsonKey(name: 'model_type') String? modelType,
    @JsonKey(name: 'model_id') int? modelId,
    @JsonKey(name: 'collection_name') String? collectionName,
    @JsonKey(name: 'name') String? name,
    @JsonKey(name: 'file_name') String? fileName,
    @JsonKey(name: 'mime_type') String? mimeType,
    @JsonKey(name: 'disk') String? disk,
    @JsonKey(name: 'conversions_disk') String? conversionsDisk,
    @JsonKey(name: 'size') int? size,
    @JsonKey(name: 'created_at') DateTime? createdAt,
    @JsonKey(name: 'updated_at') DateTime? updatedAt,
    @JsonKey(name: 'original_url') String? originalUrl,
    @JsonKey(name: 'preview_url') String? previewUrl,
  }) = _Media;

  factory Media.fromJson(Map<String, dynamic> json) => _$MediaFromJson(json);
}
