// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:isar/isar.dart';
import 'package:xflutter_cli_modules_application/common/models/models.dart';

part 'meta.g.dart';

@embedded
class IsarMeta {
  DateTime? createdAt;
  DateTime? updatedAt;
  String? barcode;
  String? qrCode;

  IsarMeta({
    this.createdAt,
    this.updatedAt,
    this.barcode,
    this.qrCode,
  });
}

extension IsarMetaConverter on IsarMeta {
  /// convert [IsarMeta] to [Meta]
  Meta fromIsar() {
    return Meta(
      createdAt: createdAt,
      updatedAt: updatedAt,
      barcode: barcode,
      qrCode: qrCode,
    );
  }
}

extension MetaConverter on Meta {
  /// convert [Meta] to [IsarMeta]
  IsarMeta toIsar() {
    return IsarMeta(
      createdAt: createdAt,
      updatedAt: updatedAt,
      barcode: barcode,
      qrCode: qrCode,
    );
  }
}
