name: orders
version: 0.0.1
homepage: none
publish_to: none
description: Orders Package
environment: 
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: null
