// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import '../viewmodels/forget_password_viewmodel.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:xflutter_cli_modules_application/common/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/instance/instance_builder.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/text_fields/customized_reactive_text_field.dart';

class ForgetPasswordForm extends StatelessWidget {
  const ForgetPasswordForm({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ForgetPasswordViewModel>(
      builder: (ForgetPasswordViewModel viewModel) {
        final formGroup = viewModel.params.forgetPasswordForm;

        return ReactiveForm(
          formGroup: formGroup,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              // form fields
              Column(
                children: [
                  // email
                  CustomizedReactiveFormField<String>(
                    formControlName: 'email',
                    labelText: 'email'.tr(),
                    keyboardType: TextInputType.emailAddress,
                    textInputAction: TextInputAction.done,
                    onSubmitted: (_) {},
                  ),
                  const SizedBox(height: formSpacing),
                ],
              ),

              // submit widget
              SizedBox(
                width: double.infinity,
                child: CustomizedButton(
                  child: Text('next'.tr()),
                  callback: () {
                    if (formGroup.valid) {
                      viewModel.submit();
                    } else {
                      formGroup.markAllAsTouched();
                    }
                  },
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
