// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'meta.freezed.dart';
part 'meta.g.dart';

// ----------(json)----------
/*
{
  "createdAt": "2024-05-23T08:56:21.618Z",
  "updatedAt": "2024-05-23T08:56:21.618Z",
  "barcode": "9164035109868",
  "qrCode": "https://assets.dummyjson.com/public/qr-code.png"
} 
*/
// --------------------------
@freezed
class Meta with _$Meta {
  const factory Meta({
    DateTime? createdAt,
    DateTime? updatedAt,
    String? barcode,
    String? qrCode,
  }) = _Meta;

  factory Meta.fromJson(Map<String, dynamic> json) => _$MetaFromJson(json);
}
