// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:objectbox/objectbox.dart';
import 'package:products/src/data/models/entities/review/review.dart';

@Entity()
class LocalReview {
  @Id()
  int id = 0;
  int? rating;
  String? comment;
  @Property(type: PropertyType.date)
  DateTime? date;
  String? reviewerName;
  String? reviewerEmail;

  LocalReview({this.id = 0, this.rating, this.comment, this.date, this.reviewerName, this.reviewerEmail});

  /// convert [Review] to [LocalReview]
  factory LocalReview.fromEntity(Review entity) {
    final item = LocalReview(
      rating: entity.rating,
      comment: entity.comment,
      date: entity.date,
      reviewerName: entity.reviewerName,
      reviewerEmail: entity.reviewerEmail,
    );

    return item;
  }

  /// convert [LocalReview] to [Review]
  Review fromLocal() => Review(rating: rating, comment: comment, date: date, reviewerName: reviewerName, reviewerEmail: reviewerEmail);
}
