// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:xflutter_cli_modules_application/core/utilities/di/di.dart';
import 'models/isar_models.dart';

class AppIsar {
  /// initialize new [Isar] instance and make it singleton.
  static Future<void> initialize() async {
    final instance = await _openIsar();
    putInstance<Isar>(instance);
  }

  /// Open a new [Isar] instance.
  static Future<Isar> _openIsar() async {
    final directory = await getApplicationDocumentsDirectory();
    final isar = await Isar.open(
      [
        IsarProductSchema,
      ],
      directory: directory.path,
    );
    return isar;
  }
}

/// get limitation offset depending on [perPage] and selected [page]
int offset(int page, int perPage) => ((perPage * page) - perPage).toInt();
