// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_modules_application/common/ui/widgets/buttons/text_button.dart';
import 'package:xflutter_cli_modules_application/common/ui/resources/themes/theme.dart';
import 'package:xflutter_cli_modules_application/common/router/app_router.dart';
import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import '../viewmodels/login_viewmodel.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:xflutter_cli_modules_application/common/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/instance/instance_builder.dart';
import 'package:xflutter_cli_modules_application/common/ui/widgets/text_fields/customized_reactive_text_field.dart';

class LoginForm extends StatelessWidget {
  const LoginForm({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginViewModel>(
      builder: (LoginViewModel viewModel) {
        final formGroup = viewModel.params.loginForm;

        return ReactiveForm(
          formGroup: formGroup,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              // form fields
              Column(
                children: [
                  // email
                  CustomizedReactiveFormField<String>(
                    formControlName: 'email',
                    labelText: 'email'.tr(),
                    keyboardType: TextInputType.emailAddress,
                    textInputAction: TextInputAction.next,
                    onSubmitted: (_) => formGroup.focus('password'),
                  ),
                  const SizedBox(height: formSpacing),

                  // password
                  CustomizedReactiveFormField<String>(
                    formControlName: 'password',
                    labelText: 'password'.tr(),
                    keyboardType: TextInputType.text,
                    textInputAction: TextInputAction.done,
                    obscureText: true,
                    onSubmitted: (_) {},
                  ),
                  const SizedBox(height: formSpacing),
                  Align(
                    alignment: AlignmentDirectional.centerStart,
                    child: AppTextButton(
                      text: 'forget_password'.tr(),
                      textStyle: smallTextStyle,
                      callback: () {
                        appRouter.push(const ForgetPassword());
                      },
                    ),
                  ),
                  const SizedBox(height: formSpacing),
                ],
              ),

              // submit widget
              Column(
                children: [
                  SizedBox(
                    width: double.infinity,
                    child: CustomizedButton(
                      child: Text('next'.tr()),
                      callback: () {
                        if (formGroup.valid) {
                          viewModel.submit();
                        } else {
                          formGroup.markAllAsTouched();
                        }
                      },
                    ),
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text('not_have_account'.tr(), style: smallTextStyle),
                      AppTextButton(
                        text: 'create_account'.tr(),
                        textStyle: smallTextStyle,
                        callback: () {
                          appRouter.push(const Register());
                        },
                      ),
                    ],
                  )
                ],
              ),
            ],
          ),
        );
      },
    );
  }
}
