// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:dio/dio.dart';

abstract class AppEnvironment {
  /// size of chuck when fetch data with pagination
  int get perPage => 25;

  /// [BaseOptions.baseUrl] for [Dio]
  String get baseUrl;
}

class TestEnvironment extends AppEnvironment {
  @override
  String get baseUrl => 'https://test.backend.com';
}

class DevelopmentEnvironment extends AppEnvironment {
  @override
  String get baseUrl => 'https://development.backend.com';
}

class ProductionEnvironment extends AppEnvironment {
  @override
  String get baseUrl => 'https://live.backend.com';
}
