// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:xflutter_cli_test_application/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_test_application/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_test_application/ui/widgets/text_fields/customized_reactive_text_field.dart';
import '../viewmodels/forget_password_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class ForgetPasswordForm extends StatelessWidget {
  const ForgetPasswordForm({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<ForgetPasswordViewModel>(
      builder: (viewModel) => ReactiveForm(
        formGroup: viewModel.params.forgetPasswordForm,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Column(
              children: [
                CustomizedReactiveFormField(
                  formControlName: 'email',
                  labelText: 'email'.tr(),
                  keyboardType: TextInputType.emailAddress,
                  textInputAction: TextInputAction.done,
                  onSubmitted: (control) {},
                ),
                const SizedBox(height: formSpacing),
              ],
            ),
            ReactiveFormConsumer(
              builder: (context, form, child) => SizedBox(
                width: double.infinity,
                child: CustomizedButton(
                  child: Text('next'.tr()),
                  callback: () {
                    if (form.valid) {
                      viewModel.submit();
                    } else {
                      form.markAllAsTouched();
                    }
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
