// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/ui/screens/products/widgets/product_form.dart';
import 'package:xflutter_cli_test_application/ui/resources/themes/theme.dart';
import 'package:xflutter_cli_test_application/ui/widgets/core/base_scrollview.dart';
import 'package:flutter/material.dart';
import '../viewmodels/create_product_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class CreateProductMobileScreen extends StatelessWidget {
  const CreateProductMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<CreateProductViewModel>(
      builder: (CreateProductViewModel viewModel) {
        return BaseScrollView(
          padding: adaptivePadding,
          child: ProductForm(
            submit: viewModel.submit,
          ),
        );
      },
    );
  }
}
