/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:xflutter_cli_test_application/environment/environment.dart';

class HttpInterceptor extends InterceptorsWrapper {
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) async {
    final httpHeaders = {
      'Accept': 'application/json',
      // TODO: add authorization token to http-headers
      'Authorization': 'Bearer {token}',
    };
    options.headers.addAll(httpHeaders);
    options.connectTimeout = const Duration(seconds: 60);
    options.receiveTimeout = const Duration(seconds: 60);
    options.sendTimeout = const Duration(seconds: 60);
    options.baseUrl = Environment.apiUrl;
    super.onRequest(options, handler);
  }

  @override
  Future onError(DioException err, ErrorInterceptorHandler handler) async {
    if (err.response?.statusCode == 401) {
      // TODO: handle Unauthorized Response
    }
    super.onError(err, handler);
  }
}