import 'package:xflutter_cli_test_application/extensions/live_data_extension.dart'; // Generated By XFlutter Cli.

//
// more info: https://xflutter-cli.com
// declare and manage viewModel-liveData variables.
//
// see: https://pub.dev/packages/flutterx_live_data
//
// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e
class VerifyPinCodeParams {
  var email = '';
  final code = ''.liveData;
}
