// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:reactive_forms/reactive_forms.dart';

extension FormGroupUtils on FormGroup {
  T? getControlValue<T>(String formControlName) {
    final value = controls[formControlName]?.value;
    if (value != null) return value as T;
    return null;
  }
}
