name: flutter_monorepo_workspace

workspace:
  - packages/orders
  - packages/products
  - apps/admin_app
  - packages/core
  - apps/customer_app

environment:
  sdk: ^3.10.7

dependency_overrides:
  # fix build_runner version conflict
  path_provider_foundation: 2.5.1
dev_dependencies:
  path: ^1.9.0
  build_runner: ^2.5.4
  melos: ^7.3.0

