/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:redacted/redacted.dart';
import 'product_card_widget.dart';
import 'package:test_app/models/models.dart';

class ProductShimmerWidget extends StatelessWidget {
  final int itemCount;
  const ProductShimmerWidget({this.itemCount = 4, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: itemCount,
      itemBuilder: (context, index) => const ProductCardWidget(
        Product(thumbnail: "", title: "New Product", price: 100),
      ).redacted(
        context: context,
        redact: true,
        configuration: RedactedConfiguration(
          animationDuration: const Duration(milliseconds: 600),
          autoFillText: "Product",
        ),
      ),
    );
  }
}
