// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/ui/resources/themes/theme.dart';
import 'package:xflutter_cli_test_application/ui/widgets/core/base_scrollview.dart';
import 'package:xflutter_cli_test_application/ui/widgets/text_fields/verify_pin_code_widget.dart';
import 'package:flutter/material.dart';
import '../viewmodels/verify_pin_code_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class VerifyPinCodeTabletScreen extends StatelessWidget {
  const VerifyPinCodeTabletScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<VerifyPinCodeViewModel>(
      builder: (VerifyPinCodeViewModel viewModel) {
        return BaseScrollView(
          padding: adaptivePadding,
          child: VerifyPinCodeWidget(
            code: viewModel.params.code,
            receiver: viewModel.params.phone,
            onChanged: viewModel.onPinCodeChanged,
            onSubmit: viewModel.submitVerificationCode,
            onResendCode: viewModel.requestVerificationCode,
          ),
        );
      },
    );
  }
}
