name: widgets
version: 0.0.1
homepage: none
publish_to: none
description: generate reusable widgets like buttons, loaders and more
environment: 
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter_animate: ^4.1.1+1
  flutter_spinkit: ^5.1.0
  flutterx_live_data: ^1.9.2
  implicitly_animated_reorderable_list_2: ^0.6.0
  animated_infinite_scroll_pagination: ^0.3.9
  reactive_forms: ^16.1.0
  models: 
    path: ../../packages/models
  utilities: 
    path: ../../packages/utilities
  theme: 
    path: ../../packages/theme
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
flutter: null
