name: core
version: 0.0.1
homepage: none
publish_to: none
description: Core Package
environment: 
  sdk: ^3.5.1
  flutter: '>=1.17.0'
dependencies: 
  pretty_dio_logger: ^1.4.0
  dio: ^5.1.2
  easy_localization: ^3.0.1
  flutter_animate: ^4.1.1+1
  flutter_spinkit: ^5.1.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  animated_infinite_scroll_pagination: ^1.0.3
  reactive_phone_form_field: ^4.0.0
  reactive_forms: ^17.0.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.0.15
  event_bus: ^2.0.1
  flutterx_live_data: ^1.9.6
  connectivity_plus: ^6.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.1.0
  injectable: ^2.5.0
  get_it: ^8.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  freezed: ^2.5.7
  build_runner: ^2.4.11
  json_serializable: ^6.4.1
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
