// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:objectbox/objectbox.dart';
import 'package:xflutter_cli_modules_application/modules/products/data/models/entities/product/product.dart';
import 'package:xflutter_cli_modules_application/modules/products/data/models/entities/dimensions/dimensions.dart';
import 'package:xflutter_cli_modules_application/modules/products/data/models/entities/review/review.dart';
import 'package:xflutter_cli_modules_application/modules/products/data/models/entities/meta/meta.dart';
import 'dart:convert' as convert;

@Entity()
class LocalProduct {
  @Id(assignable: true)
  int id;
  String? title;
  String? description;
  String? category;
  double? price;
  double? discountPercentage;
  double? rating;
  int? stock;
  List<String>? tags;
  String? brand;
  String? sku;
  int? weight;
  String? dimensions;
  String? warrantyInformation;
  String? shippingInformation;
  String? availabilityStatus;
  List<String>? reviews;
  String? returnPolicy;
  int? minimumOrderQuantity;
  String? meta;
  List<String>? images;
  String? thumbnail;

  LocalProduct({
    required this.id,
    this.title,
    this.description,
    this.category,
    this.price,
    this.discountPercentage,
    this.rating,
    this.stock,
    this.tags,
    this.brand,
    this.sku,
    this.weight,
    this.dimensions,
    this.warrantyInformation,
    this.shippingInformation,
    this.availabilityStatus,
    this.reviews,
    this.returnPolicy,
    this.minimumOrderQuantity,
    this.meta,
    this.images,
    this.thumbnail,
  });

  /// convert [Product] to [LocalProduct]
  factory LocalProduct.fromEntity(Product entity) {
    final item = LocalProduct(
      id: entity.id ?? 0,
      title: entity.title,
      description: entity.description,
      category: entity.category,
      price: entity.price?.toDouble(),
      discountPercentage: entity.discountPercentage?.toDouble(),
      rating: entity.rating?.toDouble(),
      stock: entity.stock,
      tags: entity.tags,
      brand: entity.brand,
      sku: entity.sku,
      weight: entity.weight,
      warrantyInformation: entity.warrantyInformation,
      shippingInformation: entity.shippingInformation,
      availabilityStatus: entity.availabilityStatus,
      returnPolicy: entity.returnPolicy,
      minimumOrderQuantity: entity.minimumOrderQuantity,
      images: entity.images,
      thumbnail: entity.thumbnail,
      dimensions: convert.json.encode(entity.dimensions ?? {}),
      reviews: entity.reviews?.map((e) => convert.json.encode(e)).toList(),
      meta: convert.json.encode(entity.meta ?? {}),
    );

    return item;
  }

  /// convert [LocalProduct] to [Product]
  Product fromLocal() => Product(
    id: id,
    title: title,
    description: description,
    category: category,
    price: price,
    discountPercentage: discountPercentage,
    rating: rating,
    stock: stock,
    tags: tags,
    brand: brand,
    sku: sku,
    weight: weight,
    warrantyInformation: warrantyInformation,
    shippingInformation: shippingInformation,
    availabilityStatus: availabilityStatus,
    returnPolicy: returnPolicy,
    minimumOrderQuantity: minimumOrderQuantity,
    images: images,
    thumbnail: thumbnail,
    dimensions: Dimensions.fromJson(convert.json.decode(dimensions ?? '{}')),
    reviews: reviews?.map((e) => Review.fromJson(convert.json.decode(e))).toList(),
    meta: Meta.fromJson(convert.json.decode(meta ?? '{}')),
  );
}
