// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'full_screen_loader.dart';
import '../blur_widget.dart';

class LiveDataFullScreenLoader extends StatelessWidget {
  final LiveData<bool> loading;
  final double blur;
  const LiveDataFullScreenLoader({required this.loading, this.blur = 1.8, super.key});

  @override
  Widget build(BuildContext context) {
    return LiveDataBuilder<bool>(
      data: loading,
      builder: (context, boolean) {
        return boolean
            ? Stack(
                children: [
                  BlurWidget(width: double.infinity, height: double.infinity, blur: blur),
                  const FullScreenLoader(),
                ],
              )
            : const SizedBox.shrink();
      },
    );
  }
}
