/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:isar/isar.dart';
import 'package:xflutter_cli_test_application/models/models.dart';
import '../isar_models.dart';

part 'product.g.dart';

@collection
class IsarProduct {
  Id? isarId;

  @Index(unique: true, replace: true)
  int? id;
  String? name;
  double? price;
  double? originalPrice;
  String? description;
  String? color;
  String? size;
  String? status;
  DateTime? createdAt;
  IsarUser? user;
  List<IsarMedia>? media;

  IsarLink<IsarCategory> category = IsarLink();

  IsarProduct({
    this.id,
    this.name,
    this.price,
    this.originalPrice,
    this.description,
    this.color,
    this.size,
    this.status,
    this.createdAt,
    this.user,
    this.media,
  });
}

extension IsarProductConverter on IsarProduct {
  /// convert [IsarProduct] to [Product]
  Product fromIsar() {
    return Product(
      id: id,
      name: name,
      price: price,
      originalPrice: originalPrice,
      description: description,
      color: color,
      size: size,
      status: status,
      createdAt: createdAt,
      user: user?.fromIsar(),
      media: media?.map((e) => e.fromIsar()).toList(),
      category: category.value?.fromIsar(),
    );
  }
}

extension ProductConverter on Product {
  /// convert [Product] to [IsarProduct]
  IsarProduct toIsar() {
    return IsarProduct(
      id: id,
      name: name,
      price: price?.toDouble(),
      originalPrice: originalPrice?.toDouble(),
      description: description,
      color: color,
      size: size,
      status: status,
      createdAt: createdAt,
      user: user?.toIsar(),
      media: media?.map((e) => e.toIsar()).toList(),
    );
  }
}
