// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';

class AppBackButton extends StatelessWidget {
  final Color? color;
  final bool force;
  final Function()? backHandler;

  const AppBackButton({
    this.color,
    this.force = false,
    this.backHandler,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Navigator.canPop(context) || force
        ? GestureDetector(
            onTap: () => backHandler?.call() ?? Navigator.pop(context),
            child: const Padding(padding: EdgeInsets.all(6), child: Icon(Icons.arrow_back)),
          )
        : const SizedBox(height: 32);
  }
}
