// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:products/src/data/models/entities/dimensions/dimensions.dart';
import 'package:products/src/data/models/entities/review/review.dart';
import 'package:products/src/data/models/entities/meta/meta.dart';
part 'product.freezed.dart';
part 'product.g.dart';

@freezed
class Product with _$Product {
  const factory Product({
    @JsonKey(name: 'id') int? id,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'category') String? category,
    @JsonKey(name: 'price') num? price,
    @JsonKey(name: 'discountPercentage') num? discountPercentage,
    @JsonKey(name: 'rating') num? rating,
    @JsonKey(name: 'stock') int? stock,
    @JsonKey(name: 'tags') List<String>? tags,
    @JsonKey(name: 'brand') String? brand,
    @JsonKey(name: 'sku') String? sku,
    @JsonKey(name: 'weight') int? weight,
    @JsonKey(name: 'dimensions') Dimensions? dimensions,
    @JsonKey(name: 'warrantyInformation') String? warrantyInformation,
    @JsonKey(name: 'shippingInformation') String? shippingInformation,
    @JsonKey(name: 'availabilityStatus') String? availabilityStatus,
    @JsonKey(name: 'reviews') List<Review>? reviews,
    @JsonKey(name: 'returnPolicy') String? returnPolicy,
    @JsonKey(name: 'minimumOrderQuantity') int? minimumOrderQuantity,
    @JsonKey(name: 'meta') Meta? meta,
    @JsonKey(name: 'images') List<String>? images,
    @JsonKey(name: 'thumbnail') String? thumbnail,
  }) = _Product;

  factory Product.fromJson(Map<String, dynamic> json) => _$ProductFromJson(json);
}
