name: products
version: 0.0.1
homepage: none
publish_to: none
description: Products Package
environment: 
  sdk: ^3.5.1
  flutter: '>=1.17.0'
dependencies:
  redacted: ^1.0.12
  animated_infinite_scroll_pagination: ^1.0.1
  retrofit: ^4.0.1
  get_it: ^7.2.0
  dio: ^5.1.2
  flutterx_live_data: ^1.9.2
  responsive_builder: ^0.7.0
  core:
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0 
  flutter: 
    sdk: flutter
dev_dependencies:
  retrofit_generator: ^7.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.4.11
  json_serializable: ^6.4.1 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
