// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart' as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../src/data/models/local/dimensions/local_dimensions.dart';
import '../../../src/data/models/local/meta/local_meta.dart';
import '../../../src/data/models/local/product/local_product.dart';
import '../../../src/data/models/local/review/local_review.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 104962965997141550),
    name: 'LocalDimensions',
    lastPropertyId: const obx_int.IdUid(4, 2660370483705824403),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 3960245470070566219), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 8918540251763808056), name: 'width', type: 8, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 3396297559515432811), name: 'height', type: 8, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 2660370483705824403), name: 'depth', type: 8, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4372946423018527409),
    name: 'LocalMeta',
    lastPropertyId: const obx_int.IdUid(5, 6501150960600091387),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 4155359654159165), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 1400059141257552635), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 2225698168235910474), name: 'updatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 2696226517279801697), name: 'barcode', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 6501150960600091387), name: 'qrCode', type: 9, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7803196425466444285),
    name: 'LocalProduct',
    lastPropertyId: const obx_int.IdUid(21, 3827544426033728238),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 9094603482268892450), name: 'id', type: 6, flags: 129),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 1455042890205195442), name: 'title', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 3998039406420956223), name: 'description', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 5094782666636691185), name: 'category', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 9023394141263089313), name: 'price', type: 8, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 4172747153913525449), name: 'discountPercentage', type: 8, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 8426980494473998124), name: 'rating', type: 8, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 6397051353273804014), name: 'stock', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(9, 4385459039798092659), name: 'tags', type: 30, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(10, 4702699787083868902), name: 'brand', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(11, 813420732344419138), name: 'sku', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(12, 5214532323706359694), name: 'weight', type: 6, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1233225812099579638),
        name: 'toOneDimensionsId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7695097242651049403),
        relationField: 'toOneDimensions',
        relationTarget: 'LocalDimensions',
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(14, 664163659287190058), name: 'warrantyInformation', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(15, 4639462083671049947), name: 'shippingInformation', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(16, 5856848782409163979), name: 'availabilityStatus', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(17, 9005334799546874547), name: 'returnPolicy', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(18, 1488070347012803625), name: 'minimumOrderQuantity', type: 6, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5504510225154717139),
        name: 'toOneMetaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3257443784954279306),
        relationField: 'toOneMeta',
        relationTarget: 'LocalMeta',
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(20, 8148793497669016384), name: 'images', type: 30, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(21, 3827544426033728238), name: 'thumbnail', type: 9, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 2090418851941757064),
        name: 'toManyReviews',
        targetId: const obx_int.IdUid(4, 288216155754310647),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 288216155754310647),
    name: 'LocalReview',
    lastPropertyId: const obx_int.IdUid(6, 491144282308339648),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 6544587439090591207), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 9152844163821629320), name: 'rating', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 1466382094737289953), name: 'comment', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 4613646874858745406), name: 'date', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 4861320412661939260), name: 'reviewerName', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 491144282308339648), name: 'reviewerEmail', type: 9, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 288216155754310647),
    lastIndexId: const obx_int.IdUid(2, 3257443784954279306),
    lastRelationId: const obx_int.IdUid(1, 2090418851941757064),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LocalDimensions: obx_int.EntityDefinition<LocalDimensions>(
      model: _entities[0],
      toOneRelations: (LocalDimensions object) => [],
      toManyRelations: (LocalDimensions object) => {},
      getId: (LocalDimensions object) => object.id,
      setId: (LocalDimensions object, int id) {
        object.id = id;
      },
      objectToFB: (LocalDimensions object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.width);
        fbb.addFloat64(2, object.height);
        fbb.addFloat64(3, object.depth);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final widthParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 6);
        final heightParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 8);
        final depthParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 10);
        final object = LocalDimensions(id: idParam, width: widthParam, height: heightParam, depth: depthParam);

        return object;
      },
    ),
    LocalMeta: obx_int.EntityDefinition<LocalMeta>(
      model: _entities[1],
      toOneRelations: (LocalMeta object) => [],
      toManyRelations: (LocalMeta object) => {},
      getId: (LocalMeta object) => object.id,
      setId: (LocalMeta object, int id) {
        object.id = id;
      },
      objectToFB: (LocalMeta object, fb.Builder fbb) {
        final barcodeOffset = object.barcode == null ? null : fbb.writeString(object.barcode!);
        final qrCodeOffset = object.qrCode == null ? null : fbb.writeString(object.qrCode!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(2, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(3, barcodeOffset);
        fbb.addOffset(4, qrCodeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final createdAtParam = createdAtValue == null ? null : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final updatedAtParam = updatedAtValue == null ? null : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final barcodeParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10);
        final qrCodeParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 12);
        final object = LocalMeta(
          id: idParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          barcode: barcodeParam,
          qrCode: qrCodeParam,
        );

        return object;
      },
    ),
    LocalProduct: obx_int.EntityDefinition<LocalProduct>(
      model: _entities[2],
      toOneRelations: (LocalProduct object) => [object.toOneDimensions, object.toOneMeta],
      toManyRelations: (LocalProduct object) => {obx_int.RelInfo<LocalProduct>.toMany(1, object.id): object.toManyReviews},
      getId: (LocalProduct object) => object.id,
      setId: (LocalProduct object, int id) {
        object.id = id;
      },
      objectToFB: (LocalProduct object, fb.Builder fbb) {
        final titleOffset = object.title == null ? null : fbb.writeString(object.title!);
        final descriptionOffset = object.description == null ? null : fbb.writeString(object.description!);
        final categoryOffset = object.category == null ? null : fbb.writeString(object.category!);
        final tagsOffset = object.tags == null ? null : fbb.writeList(object.tags!.map(fbb.writeString).toList(growable: false));
        final brandOffset = object.brand == null ? null : fbb.writeString(object.brand!);
        final skuOffset = object.sku == null ? null : fbb.writeString(object.sku!);
        final warrantyInformationOffset = object.warrantyInformation == null ? null : fbb.writeString(object.warrantyInformation!);
        final shippingInformationOffset = object.shippingInformation == null ? null : fbb.writeString(object.shippingInformation!);
        final availabilityStatusOffset = object.availabilityStatus == null ? null : fbb.writeString(object.availabilityStatus!);
        final returnPolicyOffset = object.returnPolicy == null ? null : fbb.writeString(object.returnPolicy!);
        final imagesOffset = object.images == null ? null : fbb.writeList(object.images!.map(fbb.writeString).toList(growable: false));
        final thumbnailOffset = object.thumbnail == null ? null : fbb.writeString(object.thumbnail!);
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addFloat64(4, object.price);
        fbb.addFloat64(5, object.discountPercentage);
        fbb.addFloat64(6, object.rating);
        fbb.addInt64(7, object.stock);
        fbb.addOffset(8, tagsOffset);
        fbb.addOffset(9, brandOffset);
        fbb.addOffset(10, skuOffset);
        fbb.addInt64(11, object.weight);
        fbb.addInt64(12, object.toOneDimensions.targetId);
        fbb.addOffset(13, warrantyInformationOffset);
        fbb.addOffset(14, shippingInformationOffset);
        fbb.addOffset(15, availabilityStatusOffset);
        fbb.addOffset(16, returnPolicyOffset);
        fbb.addInt64(17, object.minimumOrderQuantity);
        fbb.addInt64(18, object.toOneMeta.targetId);
        fbb.addOffset(19, imagesOffset);
        fbb.addOffset(20, thumbnailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final titleParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 6);
        final descriptionParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 8);
        final categoryParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10);
        final priceParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 12);
        final discountPercentageParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 14);
        final ratingParam = const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 16);
        final stockParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final brandParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22);
        final skuParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 24);
        final weightParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
        final warrantyInformationParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 30);
        final shippingInformationParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 32);
        final availabilityStatusParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 34);
        final returnPolicyParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 36);
        final minimumOrderQuantityParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 38);
        final imagesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final thumbnailParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 44);
        final object = LocalProduct(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          category: categoryParam,
          price: priceParam,
          discountPercentage: discountPercentageParam,
          rating: ratingParam,
          stock: stockParam,
          tags: tagsParam,
          brand: brandParam,
          sku: skuParam,
          weight: weightParam,
          warrantyInformation: warrantyInformationParam,
          shippingInformation: shippingInformationParam,
          availabilityStatus: availabilityStatusParam,
          returnPolicy: returnPolicyParam,
          minimumOrderQuantity: minimumOrderQuantityParam,
          images: imagesParam,
          thumbnail: thumbnailParam,
        );
        object.toOneDimensions.targetId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
        object.toOneDimensions.attach(store);
        object.toOneMeta.targetId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 40, 0);
        object.toOneMeta.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<LocalProduct>(
          object.toManyReviews,
          store,
          obx_int.RelInfo<LocalProduct>.toMany(1, object.id),
        );
        return object;
      },
    ),
    LocalReview: obx_int.EntityDefinition<LocalReview>(
      model: _entities[3],
      toOneRelations: (LocalReview object) => [],
      toManyRelations: (LocalReview object) => {},
      getId: (LocalReview object) => object.id,
      setId: (LocalReview object, int id) {
        object.id = id;
      },
      objectToFB: (LocalReview object, fb.Builder fbb) {
        final commentOffset = object.comment == null ? null : fbb.writeString(object.comment!);
        final reviewerNameOffset = object.reviewerName == null ? null : fbb.writeString(object.reviewerName!);
        final reviewerEmailOffset = object.reviewerEmail == null ? null : fbb.writeString(object.reviewerEmail!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.rating);
        fbb.addOffset(2, commentOffset);
        fbb.addInt64(3, object.date?.millisecondsSinceEpoch);
        fbb.addOffset(4, reviewerNameOffset);
        fbb.addOffset(5, reviewerEmailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final ratingParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
        final commentParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 8);
        final dateParam = dateValue == null ? null : DateTime.fromMillisecondsSinceEpoch(dateValue);
        final reviewerNameParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 12);
        final reviewerEmailParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 14);
        final object = LocalReview(
          id: idParam,
          rating: ratingParam,
          comment: commentParam,
          date: dateParam,
          reviewerName: reviewerNameParam,
          reviewerEmail: reviewerEmailParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalDimensions] entity fields to define ObjectBox queries.
class LocalDimensions_ {
  /// See [LocalDimensions.id].
  static final id = obx.QueryIntegerProperty<LocalDimensions>(_entities[0].properties[0]);

  /// See [LocalDimensions.width].
  static final width = obx.QueryDoubleProperty<LocalDimensions>(_entities[0].properties[1]);

  /// See [LocalDimensions.height].
  static final height = obx.QueryDoubleProperty<LocalDimensions>(_entities[0].properties[2]);

  /// See [LocalDimensions.depth].
  static final depth = obx.QueryDoubleProperty<LocalDimensions>(_entities[0].properties[3]);
}

/// [LocalMeta] entity fields to define ObjectBox queries.
class LocalMeta_ {
  /// See [LocalMeta.id].
  static final id = obx.QueryIntegerProperty<LocalMeta>(_entities[1].properties[0]);

  /// See [LocalMeta.createdAt].
  static final createdAt = obx.QueryDateProperty<LocalMeta>(_entities[1].properties[1]);

  /// See [LocalMeta.updatedAt].
  static final updatedAt = obx.QueryDateProperty<LocalMeta>(_entities[1].properties[2]);

  /// See [LocalMeta.barcode].
  static final barcode = obx.QueryStringProperty<LocalMeta>(_entities[1].properties[3]);

  /// See [LocalMeta.qrCode].
  static final qrCode = obx.QueryStringProperty<LocalMeta>(_entities[1].properties[4]);
}

/// [LocalProduct] entity fields to define ObjectBox queries.
class LocalProduct_ {
  /// See [LocalProduct.id].
  static final id = obx.QueryIntegerProperty<LocalProduct>(_entities[2].properties[0]);

  /// See [LocalProduct.title].
  static final title = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[1]);

  /// See [LocalProduct.description].
  static final description = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[2]);

  /// See [LocalProduct.category].
  static final category = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[3]);

  /// See [LocalProduct.price].
  static final price = obx.QueryDoubleProperty<LocalProduct>(_entities[2].properties[4]);

  /// See [LocalProduct.discountPercentage].
  static final discountPercentage = obx.QueryDoubleProperty<LocalProduct>(_entities[2].properties[5]);

  /// See [LocalProduct.rating].
  static final rating = obx.QueryDoubleProperty<LocalProduct>(_entities[2].properties[6]);

  /// See [LocalProduct.stock].
  static final stock = obx.QueryIntegerProperty<LocalProduct>(_entities[2].properties[7]);

  /// See [LocalProduct.tags].
  static final tags = obx.QueryStringVectorProperty<LocalProduct>(_entities[2].properties[8]);

  /// See [LocalProduct.brand].
  static final brand = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[9]);

  /// See [LocalProduct.sku].
  static final sku = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[10]);

  /// See [LocalProduct.weight].
  static final weight = obx.QueryIntegerProperty<LocalProduct>(_entities[2].properties[11]);

  /// See [LocalProduct.toOneDimensions].
  static final toOneDimensions = obx.QueryRelationToOne<LocalProduct, LocalDimensions>(_entities[2].properties[12]);

  /// See [LocalProduct.warrantyInformation].
  static final warrantyInformation = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[13]);

  /// See [LocalProduct.shippingInformation].
  static final shippingInformation = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[14]);

  /// See [LocalProduct.availabilityStatus].
  static final availabilityStatus = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[15]);

  /// See [LocalProduct.returnPolicy].
  static final returnPolicy = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[16]);

  /// See [LocalProduct.minimumOrderQuantity].
  static final minimumOrderQuantity = obx.QueryIntegerProperty<LocalProduct>(_entities[2].properties[17]);

  /// See [LocalProduct.toOneMeta].
  static final toOneMeta = obx.QueryRelationToOne<LocalProduct, LocalMeta>(_entities[2].properties[18]);

  /// See [LocalProduct.images].
  static final images = obx.QueryStringVectorProperty<LocalProduct>(_entities[2].properties[19]);

  /// See [LocalProduct.thumbnail].
  static final thumbnail = obx.QueryStringProperty<LocalProduct>(_entities[2].properties[20]);

  /// see [LocalProduct.toManyReviews]
  static final toManyReviews = obx.QueryRelationToMany<LocalProduct, LocalReview>(_entities[2].relations[0]);
}

/// [LocalReview] entity fields to define ObjectBox queries.
class LocalReview_ {
  /// See [LocalReview.id].
  static final id = obx.QueryIntegerProperty<LocalReview>(_entities[3].properties[0]);

  /// See [LocalReview.rating].
  static final rating = obx.QueryIntegerProperty<LocalReview>(_entities[3].properties[1]);

  /// See [LocalReview.comment].
  static final comment = obx.QueryStringProperty<LocalReview>(_entities[3].properties[2]);

  /// See [LocalReview.date].
  static final date = obx.QueryDateProperty<LocalReview>(_entities[3].properties[3]);

  /// See [LocalReview.reviewerName].
  static final reviewerName = obx.QueryStringProperty<LocalReview>(_entities[3].properties[4]);

  /// See [LocalReview.reviewerEmail].
  static final reviewerEmail = obx.QueryStringProperty<LocalReview>(_entities[3].properties[5]);
}
