// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:xflutter_cli_test_application/router/app_router.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import './viewmodels/verify_pin_code_viewmodel.dart';
import 'package:auto_route/auto_route.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'mobile/verify_pin_code_mobile_screen.dart';
import 'tablet/verify_pin_code_tablet_screen.dart';
import 'package:xflutter_cli_test_application/data/models/di/di_scope/di_scope.dart';
import 'package:xflutter_cli_test_application/ui/widgets/loaders/live_data_loader.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/lifecycle_owner.dart';
import 'package:xflutter_cli_test_application/extensions/di_extension.dart';
import 'package:xflutter_cli_test_application/di/app_injectable.config.dart';
import 'package:xflutter_cli_test_application/ui/widgets/core/base_appbar.dart';

@RoutePage(name: 'verifyPinCode')
class VerifyPinCodeScreen extends StatefulWidget {
  final String phone;
  final PageRouteInfo? pageRoute;

  const VerifyPinCodeScreen({required this.phone, this.pageRoute, super.key});

  @override
  State<VerifyPinCodeScreen> createState() => _VerifyPinCodeScreenState();
}

class _VerifyPinCodeScreenState extends State<VerifyPinCodeScreen>
    with LifecycleOwner<VerifyPinCodeScreen, VerifyPinCodeViewModel>, ObserverMixin {
  /// handle verify response, navigate to destination route
  Future<void> _handleVerifyResponse(dynamic result) async {
    if (widget.pageRoute == null) return;
    if (result == null) return;

    // clear injected dependencies
    await dropScope(diScope);
    // navigate to destination
    appRouter.replaceAll([widget.pageRoute!]);
  }

  @override
  void observeChanges(ObserverMixin observer) {
    viewModel.params.result.observe(observer, (value) async {
      await _handleVerifyResponse(value);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // screen body
        Scaffold(
          appBar: BaseAppBar(title: 'verify_pin_code'.tr()),
          body: SafeArea(
            child: ScreenTypeLayout.builder(mobile: (_) => VerifyPinCodeMobileScreen(), tablet: (_) => VerifyPinCodeTabletScreen()),
          ),
        ),

        // full-screen loader
        LiveDataFullScreenLoader(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  void onInitState() {
    viewModel.params.phone = widget.phone;
    super.onInitState();
  }

  @override
  DiScope get diScope => DiScope(name: 'verifyPinCode', factory: getIt.initVerifyPinCodeScope, dependencies: []);
}
