// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

// ----------(json)----------
/*
{
  "id": 6,
  "full_name": "Skyla Schuppe",
  "email": "theller@example.com",
  "phone": "1-847-614-2172",
  "created_at": "2023-08-01T17:39:54.000000Z"
} 
*/
// --------------------------
@freezed
class User with _$User {
  const factory User({
    int? id,
    String? fullName,
    String? email,
    String? phone,
    DateTime? createdAt,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
