// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_test_application/ui/screens/addresses/widgets/address_form.dart';
import 'package:xflutter_cli_test_application/ui/widgets/core/base_scrollview.dart';
import '../viewmodels/addresses_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class AddressesMobileScreen extends StatelessWidget {
  const AddressesMobileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<AddressesViewModel>(
      builder: (viewModel) => const BaseScrollView(
        child: AddressForm(),
      ),
    );
  }
}
