// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import './viewmodels/products_list_viewmodel.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'mobile/products_list_mobile_screen.dart';
import 'package:core/core.dart';
import 'package:products/src/di/products_injectable.config.dart';

class ProductsListScreen extends StatefulWidget {
  const ProductsListScreen({super.key});

  @override
  State<ProductsListScreen> createState() => _ProductsListScreenState();
}

class _ProductsListScreenState extends State<ProductsListScreen>
    with LifecycleOwner<ProductsListScreen, ProductsListViewModel>, ObserverMixin {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // screen body
        BaseScaffold(
          builder: (context, theme) => SafeArea(
            child: ScreenTypeLayout.builder(
              mobile: (_) => const ProductsListMobileScreen(),
            ),
          ),
        ),

        // full-screen loader
        LiveDataFullScreenLoader(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  DiScope get diScope => DiScope(
        name: 'productsList',
        factory: getIt.initProductsListScope,
        dependencies: [
          DiScope(
            name: 'products',
            factory: getIt.initProductsScope,
          ),
          DiScope(
            name: 'productsPaging',
            factory: getIt.initProductsPagingScope,
          ),
        ],
      );
}
