/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:isar/isar.dart';
import 'package:xflutter_cli_test_application/models/models.dart';

part 'user.g.dart';

@embedded
class IsarUser {
  String? id;
  String? name;
  String? avatar;
  String? country;
  String? city;
  String? company;
  DateTime? createdAt;

  IsarUser({
    this.id,
    this.name,
    this.avatar,
    this.country,
    this.city,
    this.company,
    this.createdAt,
  });
}

extension IsarUserConverter on IsarUser {
  /// convert [IsarUser] to [User]
  User fromIsar() {
    return User(
      id: id,
      name: name,
      avatar: avatar,
      country: country,
      city: city,
      company: company,
      createdAt: createdAt,
    );
  }
}

extension UserConverter on User {
  /// convert [User] to [IsarUser]
  IsarUser toIsar() {
    return IsarUser(
      id: id,
      name: name,
      avatar: avatar,
      country: country,
      city: city,
      company: company,
      createdAt: createdAt,
    );
  }
}
