// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'product_card_widget.dart';
import 'product_redacted_widget.dart';
import 'package:core/core.dart';
import 'package:products/src/mediators/paging/products_paging_controller.dart';
import 'package:products/src/data/models/entities/product/product.dart';

class ProductsListWidget extends StatelessWidget {
  final ProductsPagingController controller;
  final Function(Product product) onUpdate;
  final Function(Product product) onDelete;
  final Function(Product product) onPressed;

  const ProductsListWidget({required this.onUpdate, required this.onDelete, required this.onPressed, required this.controller, super.key});

  @override
  Widget build(BuildContext context) {
    return InfiniteScrollView<Product, ProductsPagingController>(
      controller: controller,
      loadingWidget: const ProductRedactedWidget(),
      itemBuilder: (BuildContext context, Product item, int index) => ProductCardWidget(
        item,
        onUpdate: () => onUpdate(item),
        onDelete: () => showConformationDialog(
          context: context,
          title: 'delete_product_title'.tr(),
          content: 'delete_product_message'.tr(),
          cancelText: 'cancel'.tr(),
          confirmText: 'delete'.tr(),
          onConfirm: () => onDelete(item),
          confirmTextStyle: const TextStyle(color: Colors.red),
        ),
      ).onClick(() => onPressed(item)),
    );
  }
}
