// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:redacted/redacted.dart';
import 'product_card_widget.dart';
import 'package:products/src/models/models.dart';

class ProductRedactedWidget extends StatelessWidget {
  final int itemCount;
  const ProductRedactedWidget({this.itemCount = 4, super.key});

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: itemCount,
      itemBuilder: (context, index) => const ProductCardWidget(Product()).redacted(
        context: context,
        redact: true,
      ),
    );
  }
}
