// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:xflutter_cli_test_application/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_test_application/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_test_application/ui/widgets/text_fields/customized_reactive_text_field.dart';
import '../viewmodels/addresses_viewmodel.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';

class AddressForm extends StatelessWidget {
  const AddressForm({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<AddressesViewModel>(
      builder: (viewModel) => ReactiveForm(
        formGroup: viewModel.params.addressForm,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Column(
              children: [
                CustomizedReactiveFormField(
                  formControlName: 'title',
                  labelText: 'title'.tr(),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.next,
                  onSubmitted: (control) => viewModel.params.addressForm.focus('description'),
                ),
                const SizedBox(height: formSpacing),
                CustomizedReactiveFormField(
                  formControlName: 'description',
                  labelText: 'description'.tr(),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.next,
                  onSubmitted: (control) => viewModel.params.addressForm.focus('city'),
                ),
                const SizedBox(height: formSpacing),
                CustomizedReactiveFormField(
                  formControlName: 'city',
                  labelText: 'city'.tr(),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.next,
                  onSubmitted: (control) => viewModel.params.addressForm.focus('street'),
                ),
                const SizedBox(height: formSpacing),
                CustomizedReactiveFormField(
                  formControlName: 'street',
                  labelText: 'street'.tr(),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.done,
                  onSubmitted: (control) {},
                ),
                const SizedBox(height: formSpacing),
              ],
            ),
            ReactiveFormConsumer(
              builder: (context, form, child) => SizedBox(
                width: double.infinity,
                child: CustomizedButton(
                  child: Text('next'.tr()),
                  callback: () {
                    if (form.valid) {
                      debugPrint(form.value.toString());
                    } else {
                      form.markAllAsTouched();
                    }
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
