// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'dart:async';
import 'package:injectable/injectable.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

@lazySingleton
class AppConnectivity {
  final _connectivity = Connectivity();
  final _isConnected = MutableLiveData<bool>(value: false);
  LiveData<bool> get isConnected => _isConnected;

  /// check if device is connected to internet
  Future<bool> isConnectingToInternet() async {
    final connectivityResult = await _connectivity.checkConnectivity();
    return !connectivityResult.contains(ConnectivityResult.none);
  }

  /// listen for connection changes
  void initialize() {
    // check if device is connected to internet
    _connectivity.onConnectivityChanged.listen((List<ConnectivityResult> event) {
      _isConnected.postValue(!event.contains(ConnectivityResult.none));
    });
  }
}
