// Generated By XFlutter Cli.
//
// more info: https://xflutter-cli.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_test_application/ui/widgets/core/base_scrollview.dart';
import 'package:xflutter_cli_test_application/ui/widgets/instance/instance_builder.dart';
import '../viewmodels/addresses_viewmodel.dart';
import '../widgets/address_form.dart';

class AddressesTabletScreen extends StatelessWidget {
  const AddressesTabletScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<AddressesViewModel>(
      builder: (viewModel) => const BaseScrollView(
        child: AddressForm(),
      ),
    );
  }
}
